name       : privoxy
version    : 3.0.27
release    : 1
source     :
    - https://kent.dl.sourceforge.net/project/ijbswa/Sources/3.0.27%20%28stable%29/privoxy-3.0.27-stable-src.tar.gz : b4503b8732d4dd41a658a0cd3352d8492d0c5bc40cf4844659bc8d36ab89d765
license    : GPL-2.0-or-later
component  : network.clients
summary    : Non-caching web proxy with advanced filtering capabilities
description: |
    Privoxy is a non-caching web proxy with advanced filtering capabilities for enhancing privacy, modifying web page data and HTTP headers, controlling access, and removing ads and other obnoxious Internet junk. Privoxy has a flexible configuration and can be customized to suit individual needs and tastes. It has application for both stand-alone systems and multi-user networks.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    sed -i 's|^confdir \.|confdir /etc/privoxy|; s|^logdir \.|logdir /var/log/privoxy|' config

    install -Dm00755 privoxy $installdir/usr/sbin/privoxy
    install -Dm00644 privoxy.1 $installdir/usr/share/man/man1/privoxy.1
    install -dm00755 $installdir/etc/privoxy/templates
    install -Dm00644 {config,*.action,*.filter,trust} $installdir/etc/privoxy
    install -Dm00644 templates/* $installdir/etc/privoxy/templates

    install -Dm00644 $pkgfiles/privoxy.service $installdir/%libdir%/systemd/system/privoxy.service
    install -Dm00644 $pkgfiles/privoxy.sysusers $installdir/%libdir%/sysusers.d/privoxy.conf
    install -Dm00644 $pkgfiles/privoxy.tmpfiles $installdir/%libdir%/tmpfiles.d/privoxy.conf

